package com.openjlpt.core.glossary

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonPrimitive
import java.security.MessageDigest

/** A dictionary word the learner can tap: headword, kana reading, English meanings, audio key. */
@Serializable
data class GlossaryWord(
    /** Headword, e.g. 持つ. */
    val w: String,
    /** Kana reading; empty when the headword is already kana. */
    val r: String = "",
    /** Up to three English senses, most common first. */
    val m: List<String> = emptyList(),
    /** Name of the pronunciation clip in assets/audio/words (without extension). */
    val a: String = "",
) {
    val headword: String get() = w
    val reading: String get() = r
    val meanings: List<String> get() = m
    val audioKey: String get() = a

    /** What text-to-speech should read when there is no recorded clip. */
    val spokenText: String get() = r.ifEmpty { w }
}

/** One tappable word inside a text. [start] and [end] are UTF-16 indices, as in a Kotlin String. */
data class WordSpan(val start: Int, val end: Int, val word: GlossaryWord)

@Serializable
private class GlossaryFile(
    val version: Int = 1,
    val words: Map<String, GlossaryWord> = emptyMap(),
    /** sha1(text) prefix -> [start, end, word key] spans. */
    val texts: Map<String, List<JsonArray>> = emptyMap(),
)

/**
 * Word spans for every Japanese text in one level's question bank, generated by
 * tools/build_assets.py. Texts are looked up by a hash of their exact (markup-free) content.
 */
class Glossary private constructor(private val file: GlossaryFile) {
    val wordCount: Int get() = file.words.size

    fun spansFor(text: String): List<WordSpan> {
        val raw = file.texts[key(text)] ?: return emptyList()
        return raw.mapNotNull { span ->
            if (span.size < 3) return@mapNotNull null
            val start = span[0].jsonPrimitive.int
            val end = span[1].jsonPrimitive.int
            val word = file.words[span[2].jsonPrimitive.content] ?: return@mapNotNull null
            if (start < 0 || end > text.length || start >= end) null else WordSpan(start, end, word)
        }
    }

    companion object {
        private val json = Json { ignoreUnknownKeys = true }

        fun parse(content: String): Glossary = Glossary(json.decodeFromString(GlossaryFile.serializer(), content))

        /** First 16 hex digits of the SHA-1 of the UTF-8 text; must match tools/build_assets.py. */
        fun key(text: String): String {
            val digest = MessageDigest.getInstance("SHA-1").digest(text.toByteArray(Charsets.UTF_8))
            return digest.joinToString("") { "%02x".format(it) }.take(16)
        }
    }
}
