plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
}

// -Ppreview=true builds a test APK that installs next to the released app instead of replacing it.
val preview = providers.gradleProperty("preview").map { it.toBoolean() }.getOrElse(false)

android {
    namespace = "com.openjlpt.app"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.openjlpt.app"
        minSdk = 26
        targetSdk = 35
        // The release workflow passes the version, so each new APK installs over the previous one.
        versionCode = providers.environmentVariable("VERSION_CODE").orNull?.toInt() ?: 1
        versionName = providers.environmentVariable("VERSION_NAME").orNull ?: "0.1.0"
        resValue("string", "app_name", if (preview) "Open JLPT Preview" else "Open JLPT")
        if (preview) {
            applicationIdSuffix = ".preview"
            versionNameSuffix = "-preview"
        }
    }

    signingConfigs {
        // A shared, public key checked into the repo so every build (local or CI) has the same
        // signature and updates install without uninstalling. It is not secret: use your own
        // private key before publishing to Google Play.
        getByName("debug") {
            storeFile = file("debug.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("debug")
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }

    // Audio and the word glossary are generated by tools/build_assets.py (CI runs it before
    // building). Without them the app still works, using the phone's voice and no word taps.
    sourceSets.getByName("main").assets.srcDir("generated-assets")

    androidResources {
        // MediaPlayer reads the clips straight out of the APK, so they must stay uncompressed.
        noCompress += "webm"
    }
}

dependencies {
    implementation(project(":core"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.kotlinx.coroutines.android)

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    debugImplementation(libs.androidx.compose.ui.tooling)

    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    ksp(libs.androidx.room.compiler)

    testImplementation(libs.junit)
}
