package com.openjlpt.app.audio

import android.content.Context
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.speech.tts.TextToSpeech
import android.speech.tts.UtteranceProgressListener
import com.openjlpt.app.data.AppSettings
import com.openjlpt.app.data.AudioSource
import com.openjlpt.core.glossary.GlossaryWord
import com.openjlpt.core.model.QuestionType
import com.openjlpt.core.model.ScriptLine
import com.openjlpt.core.session.SessionQuestion
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import java.util.Locale

/** Whether the phone's Japanese text-to-speech voice can be used. */
enum class VoiceState { CHECKING, READY, MISSING }

/**
 * Plays listening questions and word pronunciations.
 *
 * Built-in recordings (assets/audio, generated by tools/build_assets.py) are used by default, so
 * audio works on every phone. The phone's Japanese text-to-speech voice is used when the user
 * prefers it in Settings, or as a fallback for anything without a recording.
 */
class ListeningPlayer(context: Context, private val settings: StateFlow<AppSettings>) {
    private val assets = context.applicationContext.assets

    private val listeningClips: Set<String> by lazy { listing(LISTENING_DIR) }
    private val wordClips: Set<String> by lazy { listing(WORDS_DIR) }

    private val _voice = MutableStateFlow(VoiceState.CHECKING)
    val voice: StateFlow<VoiceState> = _voice.asStateFlow()

    /** Id of what is playing: a question id, or "word:<headword>"; null when silent. */
    private val _playing = MutableStateFlow<String?>(null)
    val playing: StateFlow<String?> = _playing.asStateFlow()

    private var media: MediaPlayer? = null
    private var ttsRun = 0
    private var lastUtteranceId: String? = null

    private val tts: TextToSpeech = TextToSpeech(context.applicationContext) { status -> onTtsInit(status) }

    fun hasRecording(questionId: String): Boolean = "$questionId.$EXT" in listeningClips

    fun canPlay(question: SessionQuestion): Boolean =
        hasRecording(question.question.id) || _voice.value == VoiceState.READY

    /** True when this question will be read by text-to-speech rather than a recording. */
    fun usesPhoneVoice(question: SessionQuestion): Boolean {
        val recorded = hasRecording(question.question.id)
        val voiceReady = _voice.value == VoiceState.READY
        return !recorded || (settings.value.audioSource == AudioSource.PHONE_VOICE && voiceReady)
    }

    fun play(question: SessionQuestion) {
        stop()
        val id = question.question.id
        if (usesPhoneVoice(question)) {
            speak(linesFor(question), id)
        } else {
            playAsset("$LISTENING_DIR/$id.$EXT", id)
        }
    }

    fun playWord(word: GlossaryWord) {
        stop()
        val id = "word:${word.headword}"
        if (word.audioKey.isNotEmpty() && "${word.audioKey}.$EXT" in wordClips) {
            playAsset("$WORDS_DIR/${word.audioKey}.$EXT", id, applySpeed = false)
        } else {
            speak(listOf(ScriptLine("N", word.spokenText)), id)
        }
    }

    /** Playback position of a recording as a fraction from 0 to 1, or null for text-to-speech. */
    fun progress(): Float? {
        val player = media ?: return null
        return runCatching {
            val duration = player.duration
            if (duration > 0) player.currentPosition.toFloat() / duration else null
        }.getOrNull()
    }

    fun stop() {
        media?.let { runCatching { it.stop() }; it.release() }
        media = null
        if (_voice.value == VoiceState.READY) tts.stop()
        _playing.value = null
    }

    fun shutdown() {
        stop()
        tts.shutdown()
    }

    private fun playAsset(path: String, id: String, applySpeed: Boolean = true) {
        val player = MediaPlayer()
        try {
            player.setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_MEDIA)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
                    .build(),
            )
            assets.openFd(path).use { fd -> player.setDataSource(fd.fileDescriptor, fd.startOffset, fd.length) }
            player.setOnCompletionListener { finished(it) }
            player.setOnErrorListener { mp, _, _ -> finished(mp); true }
            player.prepare()
            media = player
            _playing.value = id
            player.start()
            val speed = settings.value.playbackSpeed
            if (applySpeed && speed != 1.0f) {
                player.playbackParams = player.playbackParams.setSpeed(speed)
            }
        } catch (e: Exception) {
            player.release()
            if (media === player) media = null
            _playing.value = null
        }
    }

    private fun finished(player: MediaPlayer) {
        if (media === player) {
            media = null
            _playing.value = null
        }
        player.release()
    }

    private fun speak(lines: List<ScriptLine>, id: String) {
        if (_voice.value != VoiceState.READY || lines.isEmpty()) return
        val run = ++ttsRun
        lastUtteranceId = "run$run-last"
        _playing.value = id
        tts.setSpeechRate(0.9f * settings.value.playbackSpeed)
        lines.forEachIndexed { index, line ->
            tts.setPitch(pitchFor(line.speaker))
            val isLast = index == lines.lastIndex
            tts.speak(line.text, TextToSpeech.QUEUE_ADD, null, if (isLast) "run$run-last" else "run$run-$index")
            if (!isLast) tts.playSilentUtterance(PAUSE_MS, TextToSpeech.QUEUE_ADD, "run$run-pause$index")
        }
        tts.setPitch(1.0f)
    }

    private fun onTtsInit(status: Int) {
        if (status != TextToSpeech.SUCCESS) {
            _voice.value = VoiceState.MISSING
            return
        }
        val result = tts.setLanguage(Locale.JAPAN)
        if (result == TextToSpeech.LANG_MISSING_DATA || result == TextToSpeech.LANG_NOT_SUPPORTED) {
            _voice.value = VoiceState.MISSING
            return
        }
        tts.setOnUtteranceProgressListener(object : UtteranceProgressListener() {
            override fun onStart(utteranceId: String?) = Unit

            override fun onDone(utteranceId: String?) {
                if (utteranceId == lastUtteranceId && media == null) _playing.value = null
            }

            @Deprecated("Deprecated in Java")
            override fun onError(utteranceId: String?) {
                if (media == null) _playing.value = null
            }

            override fun onStop(utteranceId: String?, interrupted: Boolean) = Unit
        })
        _voice.value = VoiceState.READY
    }

    private fun listing(dir: String): Set<String> = runCatching { assets.list(dir)?.toSet() }.getOrNull().orEmpty()

    private fun pitchFor(speaker: String): Float = when (speaker.uppercase()) {
        "M", "M1" -> 0.8f
        "M2" -> 0.7f
        "F", "F1" -> 1.25f
        "F2" -> 1.4f
        else -> 1.0f
    }

    companion object {
        private const val PAUSE_MS = 600L
        private const val EXT = "webm"
        private const val LISTENING_DIR = "audio/listening"
        private const val WORDS_DIR = "audio/words"

        /**
         * What is read aloud for a listening question, in the order used on the real test:
         * set-up, question, conversation, question again, then any choices that exist only as
         * audio. tools/build_assets.py records the built-in audio in the same order.
         */
        fun linesFor(sq: SessionQuestion): List<ScriptLine> {
            val q = sq.question
            val lines = mutableListOf<ScriptLine>()
            // For 発話表現 the situation stands in for the picture, so it is shown but not read.
            if (q.type != QuestionType.UTTERANCE) {
                q.situation?.takeIf { it.isNotBlank() }?.let { lines += ScriptLine("N", it) }
            }
            val asksFirst = q.type == QuestionType.TASK || q.type == QuestionType.POINT
            if (asksFirst && q.prompt.isNotBlank()) lines += ScriptLine("N", q.prompt)
            lines += q.script
            if (q.prompt.isNotBlank() && q.type != QuestionType.QUICK_RESPONSE) lines += ScriptLine("N", q.prompt)
            if (q.type.choicesAudioOnly) {
                sq.displayedChoices.forEachIndexed { i, choice -> lines += ScriptLine("N", "${i + 1}、$choice") }
            }
            return lines
        }
    }
}
